# Generated by Django 5.0 on 2025-06-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='line_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
