# Generated by Django 5.0 on 2025-07-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_customuser_line_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machinestatus",
            name="name",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
